### ISSUE TITLE
Conversion failure (interpretation of double float as single)

### ISSUE THREAD

**Issue by aligatoralex** [cpetrich/zs2decode#2] opened 2016-12-13 19:52 UTC
I tried converting my .zs2 file into .xml unfortunetely I got this error in Terminal:

> python zs2_to_xml.py
> Traceback (most recent call last):
>   File "zs2_to_xml.py", line 13, in <module>
>     chunks = zs2decode.parser.parse_chunks(raw_chunks)
>   File "/Library/Python/2.7/site-packages/zs2decode-0.2.dev0-py2.7.egg/zs2decode/parser.py", line 284, in parse_chunks
>     chunks = _parse_chunk_ee_subtypes(chunks, debug) # EE04, EE16, but return raw data for EE11
>   File "/Library/Python/2.7/site-packages/zs2decode-0.2.dev0-py2.7.egg/zs2decode/parser.py", line 336, in _parse_chunk_ee_subtypes
>     try: interpreted_data, type_code = _parse_data_ee_subtypes(data, debug)
>   File "/Library/Python/2.7/site-packages/zs2decode-0.2.dev0-py2.7.egg/zs2decode/parser.py", line 417, in _parse_data_ee_subtypes
>     interpreted_data=[_s2d(_unpack1('f',item)) for item in items]
>   File "/Library/Python/2.7/site-packages/zs2decode-0.2.dev0-py2.7.egg/zs2decode/parser.py", line 664, in _single_as_double
>     if _struct.pack('<f', float(value)) != start_code:
> ValueError: could not convert string to float: .

**Comment by cpetrich** [comment] 2017-08-09 09:55
I added information to the error message. Can you run it again with the most recent version in the master branch?

**Comment by nicolajbky** [comment] 2017-09-14 07:30
I too get the error message. Do you have a solution yet? It would help me a lot. Thanks for your work!!!!


Attempt failed converting '.' to float.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a51d00ed794c> in <module>()
     11 raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
     12 # convert binary chunk data into lists of Python objects
---> 13 chunks = zs2decode.parser.parse_chunks(raw_chunks)
     14 # output as XML file
     15 with io.open(xml_output_file, 'wt', encoding='utf-8') as f:

c:\python36\lib\site-packages\zs2decode-0.1-py3.6.egg\zs2decode\parser.py in parse_chunks(chunks, level, debug)
    271     chunks = _parse_chunk_types(chunks) # level 1
    272     if level >= 2:
--> 273         chunks = _parse_chunk_ee_subtypes(chunks, debug) # EE04, EE16, but return raw data for EE11
    274     if level >= 3:
    275         chunks = _parse_chunk_ee11_data_records(chunks, debug)

c:\python36\lib\site-packages\zs2decode-0.1-py3.6.egg\zs2decode\parser.py in _parse_chunk_ee_subtypes(chunks, debug)
    322         address, name, data_type, data = chunk
    323         if data_type !=u'EE': continue
--> 324         try: interpreted_data, type_code = _parse_data_ee_subtypes(data, debug)
    325         except KeyError:
    326             print('Address: 0x%X' % address)

c:\python36\lib\site-packages\zs2decode-0.1-py3.6.egg\zs2decode\parser.py in _parse_data_ee_subtypes(data, debug)
    402 
    403     if sub_type == 0x04: # 0x0004 is single precision floats
--> 404         interpreted_data=[_s2d(_unpack1('f',item)) for item in items]
    405     elif sub_type == 0x05: # 0x0005 is double precision float
    406         interpreted_data=[_unpack1('d',item) for item in items]

c:\python36\lib\site-packages\zs2decode-0.1-py3.6.egg\zs2decode\parser.py in <listcomp>(.0)
    402 
    403     if sub_type == 0x04: # 0x0004 is single precision floats
--> 404         interpreted_data=[_s2d(_unpack1('f',item)) for item in items]
    405     elif sub_type == 0x05: # 0x0005 is double precision float
    406         interpreted_data=[_unpack1('d',item) for item in items]

c:\python36\lib\site-packages\zs2decode-0.1-py3.6.egg\zs2decode\parser.py in _single_as_double(presumed_single)
    652 
    653         try:
--> 654             float_value = float(value)
    655         except ValueError:
    656             # generate output for debug

ValueError: could not convert string to float: '.'

**Comment by cpetrich** [comment] 2017-09-14 11:10
thank you for the feedback. Can you run it again with the latest version of `parser.py` from the repository, please? I added debug information.

**Comment by cpetrich** [comment] 2017-09-15 11:35
I wasn't able to reproduce this error in Python 2.7 or 3.3+. However, I've refactored the offending function. The current version is available through PyPI. Does that work for you?

**Comment by nicolajbky** [comment] 2017-09-19 06:08
Hey. Thanks for having a look into it! I did download the zip and reinstalled the package. The error remains. I also forced reinstallation through pip. No change.
I am using Python 3.6

```
import io
import zs2decode.parser
import zs2decode.util

zs2_file_name = 'probe1.zs2'
xml_output_file = 'my_data_file.xml'

# load and decompress file
data_stream = zs2decode.parser.load(zs2_file_name)
# separate binary data stream into chunks
raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
# convert binary chunk data into lists of Python objects
chunks = zs2decode.parser.parse_chunks(raw_chunks)
# output as XML file
with io.open(xml_output_file, 'wt', encoding='utf-8') as f:
    f.write( zs2decode.util.chunks_to_XML(chunks) )
```

You can find the data here: _(link removed by cpetrich)_

Did I make a mistake elsewhere?

**Comment by cpetrich** [comment] 2017-09-19 06:34
Hi, thank you for checking again, and for sharing your data file. I had no problem processing that file on either Python 2.7 or 3.6. Can you verify that
```
import zs2decode
print(zs2decode.__version__)
```
returns `0.2.0`, please?

**Comment by nicolajbky** [comment] 2017-09-19 07:45
I can confirm version `0.2.0`

**Comment by nicolajbky** [comment] 2017-09-19 07:46
Doesn't it work with jupyter notebook? I will try with IDLE now

**Comment by nicolajbky** [comment] 2017-09-19 08:17
Well.. that worked flawlessly!
IDLE: 👍 
jupyter notebook: 👎 
I am working with jupyter notebook version `4.3.0` with Python `3.6.2`

**Comment by nicolajbky** [comment] 2017-09-19 08:29
Did you work out some code to extract the sensor values for the individual tests and sensors?

Open the xml file in the web browser returns
``` 
This page contains the following errors:

error on line 117695 at column 16: error parsing attribute name
Below is a rendering of the page up to the first error.
```

also the import with `ElementTree` or `xml.dom` returns:
```
Traceback (most recent call last):

  File "c:\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-6-f853e26894c2>", line 2, in <module>
    e = xml.etree.ElementTree.parse('my_data_file.xml').getroot()

  File "c:\python36\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)

  File "c:\python36\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)

  File "<string>", line unknown
ParseError: not well-formed (invalid token): line 117695, column 15
```
The line reads `<nt&)m_CompressionType type="11" value="1"/>`

**Comment by cpetrich** [comment] 2017-09-19 10:52
thanks for checking with Idle. Not sure what's going on with Jupyter, from what you write it looks like a mix-up of different versions. I won't be able to test that any time soon.

The illegal characters in the XML element name should be fixed now.

To extract data from the XML, `raw_data_dump_from_xml.py` in the examples folder should now be able to do what you want.

Please open a separate issue if there's a problem with any of those aspects.

**Closed as completed by cpetrich** 2017-09-19 10:52 UTC

**Comment by nicolajbky** [comment] 2017-09-19 11:57
Great! Thank you very much for your work!! :-)
